baseurl = "https://jasonluo.tw"
metaDataFormat = "yaml"
title = "JasonLuo's Blog"
theme = "blist"
## Support Chinese WordCount
hasCJKLanguage = true

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
disqusShortname = "jasonluo"
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Jason Luo"
      introSubtitle = "A 30 y/o guy from Taiwan! I'm interested in tech & science such as AI, weather, crypto... I love scuba diving, traveling and dogs"
      introDy1      = "is interested in AI"
      introPhoto = "/self_cover.jpg"
      logo = "/beach.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "blog/ai_limit/"
        weight = 4

  #[languages.de]
  #  contentDir = "content/de" # Deutsch
  #  weight = 2
  #  languageName = "Deutsch"
  #  title = "Blist (mehrsprachig)"
  #  description = "Modernes Blog-Theme für Ihre Hugo-Site."
  #  [languages.de.params]
  #    introTitle = "Hallo, ich bin Katheryn Fox"
  #    introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
  #    introPhoto = "/self_cover.jpg"
  #    logo = "/blist-logo-de.png"
  #  [[languages.de.menu.main]]
  #      name = "Blog"
  #      url = "blog"
  #      weight = 1

  #  [[languages.de.menu.main]]
  #      name = "Über mich"
  #      url = "page/about/"
  #      weight = 2

  #  [[languages.de.menu.main]]
  #      name = "Tags"
  #      url = "tags"
  #      weight = 3

  #[languages.dy]
  #  contentDir = "content/dy" #Example language
  #  weight = 3
  #  languageName = "Test Language"

[params]
  # for og:img 
  images = ['self_cover.jpg']

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Jhang-Shuo Luo · All rights reserved"
  favicon = "/beach.svg"
  animatePhoto = "/self_cover450x300.jpeg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-gray-200"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "Now, I work in a weather company to develop ML/DL projects"
  twitter = "https://twitter.com/JasonLu32059153"
  linkedin = "https://www.linkedin.com/in/jasonluo0201/"
  #xing = "https://www.xing.com/profile/"
  github = "https://github.com/jasonluo-tw"
  medium = "https://medium.com/@jason830201"
  instagram = "https://www.instagram.com/jasonluo0201/"
  facebook = "https://www.facebook.com/zhangshuo.luo/"
  #reddit = "https://reddit.com/"
  #dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
