# This is a basic workflow to help you get started with Actions

name: github pages CD

on:
  push:
    branches:  
    - sources
    schedule:
      - cron: "0 12 ** SUN"

jobs:
  deploy:
    name: Deploy Github Pages
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: sources
        token: ${{ secrets.hugo_deploy_token }}
        submodules: true
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.92.1'
        
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.17.0'
        
    - name: Setup theme dependency
      run: npm install
      
    - name: Setup public
      run: git worktree add -B master public origin/master
      
    - name: Delete public
      run: rm -rf public/*
      
    - name: Build new hugo public
      run: hugo -D --gc
      
    - name: Deploy to the main branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.hugo_deploy_token }}
        publish_dir: ./public
        publish_branch: main

